---
title: "Descriptive Statistics of asset-based variables used in iwi by iwi tertiles"
author: "Pearl Ante-Testard"
date: "`r Sys.Date()`"
 # officedown yaml header
output: word_document
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, 
                          encoding   = encoding, 
                          output_dir = here::here("output")
                          )})
---


```{r clean environment, echo=FALSE}

rm(list=ls(all=TRUE))

```

```{r configuration, echo = FALSE, message=FALSE}

source(here::here("R", "0-config.R"))

```

```{r read formatted data, echo=FALSE}

df_analysis <- readRDS(file = here::here("data", "1-final",
                      "df_analysis_iwi.rds")) %>%
  dplyr::mutate(study = sub("s[0-9]*_", "", study.x)) 

# View the dataframe
colnames(df_analysis)

# Assuming df_analysis is already defined

# Function to create tertiles for each study
create_tertiles <- function(df) {
  df %>%
    filter(!is.na(iwi)) %>%
    mutate(iwi_tertile = ntile(iwi, 3))
}

# Split the data by study, apply the tertile creation, and combine the results
df_analysis <- df_analysis %>%
  split(.$study) %>%
  map_df(create_tertiles)

# Print the first few rows to verify
head(df_analysis)

```


```{r render 1 function, echo=FALSE}

# Custom render function for the variables
rndr <- function(x, name, ...) {
  if (!is.numeric(x)) return(render.categorical.default(x))
  what <- switch(name,
                 iwi = "Median (SD)"
                 #tv_iwi = "Mean (SD)",
                 #phone_iwi = "Mean (SD)",
                 #car_iwi = "Mean (SD)",
                 #bike_iwi = "Mean (SD)",
                 #cheap_iwi = "Mean (SD)",
                 #expensive_iwi = "Mean (SD)",
                 #toiletfac_iwi = "Mean (SD)",
                 #rooms_iwi = "Mean (SD)",
                 #watersource_iwi = "Mean (SD)",
                 #floormat_iwi = "Mean (SD)",
                 #elec_iwi = "Mean (SD)",
                 #ref_iwi = "Mean (SD)"
                 )
  
  parse.abbrev.render.code(c("", what))(x)
}


# Function to process each study
process_study <- function(df) {
  df %>%
    filter(!is.na(arms_maternal)) %>%
    filter(!is.na(iwi)) %>%
    mutate(arms_maternal = factor(arms_maternal, levels = c(0, 1), 
                                  labels = c("Control", "Intervention")),
           tv_iwi = factor(tv_iwi),
           phone_iwi = factor(phone_iwi),
           car_iwi = factor(car_iwi),
           bike_iwi = factor(bike_iwi),
           cheap_iwi = factor(cheap_iwi),
           expensive_iwi = factor(expensive_iwi),
           toiletfac_iwi = factor(toiletfac_iwi),
           rooms_iwi = factor(rooms_iwi),
           watersource_iwi = factor(watersource_iwi),
           floormat_iwi = factor(floormat_iwi),
           elec_iwi = factor(elec_iwi),
           ref_iwi = factor(ref_iwi)
    )
}

# Split the data by study and apply the process_study function
df_analysis_split <- df_analysis %>%
  split(.$study) %>%
  map(process_study)

# Generate table1 for each study
tables <- map(df_analysis_split, ~ table1(~ tv_iwi +
                                            phone_iwi + car_iwi + bike_iwi +
                                            cheap_iwi + expensive_iwi +
                                            watersource_iwi + toiletfac_iwi +
                                            rooms_iwi + floormat_iwi + elec_iwi + ref_iwi
                                          | iwi_tertile, data = .x, overall = FALSE, rowlabelhead = "Asset variables", render = rndr, topclass="Rtable1-grid Rtable1-shade Rtable1-times Rtable1-row"))

# Print the tables for each study
tables[[1]]
tables[[2]]
tables[[3]]
tables[[4]]
tables[[5]]
tables[[6]]
tables[[7]]
tables[[8]]
tables[[9]]
tables[[10]]
tables[[11]]
tables[[12]]
tables[[13]]
tables[[14]]
tables[[15]]
tables[[16]]
```



# Session Info
```{r session info}
sessionInfo()
```

