---
title: "Correlation between IWI and sesindex by study"
author: "Pearl Ante-Testard"
date: "`r Sys.Date()`"
output: pdf_document
  #officedown::rdocx_document
   # theme: default
    #highlight: default
    #code_folding: hide
    #toc: true
    #toc_depth: 3,,
    #toc_float:
      #collapsed: true
      #smooth_scroll: true
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, 
                          encoding   = encoding, 
                          output_dir = here::here("output")
                          )})
---

```{r clean environment, echo=FALSE}

rm(list=ls(all=TRUE))

```

```{r packages and functions, echo = TRUE, warning = FALSE}

source(here::here("R", "0-config.R"))

```

```{r read formatted data, echo=FALSE}


df_analysis <- readRDS(file = here::here("data", "1-final",
                                         "df_analysis_iwi.rds")) %>% 
  dplyr::mutate(study = sub("s[0-9]*_", "", study.x)) %>%
  select(study, pid, region, cluster, arm_primary, iwi, sesindex,
         raw_fsscore, raw_fsscat, foodinseccat) %>% 
  dplyr::filter(!is.na(iwi)) %>%
  #dplyr::filter(!is.na(sesindex)) %>%
  dplyr::filter(!is.na(raw_fsscore)) %>%
  #dplyr::filter(!is.na(raw_fsscat)) %>%
  #dplyr::filter(!is.na(foodinseccat)) %>%
  dplyr::mutate(iwi = as.numeric(iwi)) 

# Calculate the minimum and maximum of raw_fsscore
min_raw_fsscore <- min(df_analysis$raw_fsscore, na.rm = TRUE)
max_raw_fsscore <- max(df_analysis$raw_fsscore, na.rm = TRUE)

# Rescale raw_fsscore to a range of 0 to 100
df_analysis <- df_analysis %>%
  mutate(rescaled_fsscore = (raw_fsscore - min_raw_fsscore) / (max_raw_fsscore - min_raw_fsscore) * 100)

# Summary of the rescaled_fsscore
summary(df_analysis$rescaled_fsscore)
       
```

```{r correlation_and_scatter_plots, echo=FALSE, message=FALSE, warning=FALSE}

# Calculate correlation by study and arrange in ascending order
correlation_by_study <- df_analysis %>%
  group_by(study) %>%
  summarize(correlation = cor(iwi, rescaled_fsscore, use = "complete.obs", method = "spearman")) %>%
  arrange(correlation)

# Create an ordered factor for study based on correlation
df_analysis <- df_analysis %>%
  mutate(study = factor(study, levels = correlation_by_study$study))

color_palette <- c(brewer.pal(name = "Set2", n = 8), brewer.pal(name = "Dark2", n = 8))


correlation_plot <- ggplot(correlation_by_study, aes(x = reorder(study, correlation), y = correlation, fill = study)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = color_palette) +
  theme_minimal() +
  labs(
    x = "Study",
    y = "Spearman correlation"
  ) + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )

scatter_plot <- ggplot(df_analysis, aes(x = iwi, y = rescaled_fsscore, color = study)) +
  geom_point(alpha = 0.2) +
  facet_wrap(~ study, scales = "free") +
  scale_color_manual(values = color_palette) +
  theme_minimal() +
  labs(
    title = "Correlation between IWI and fsscore by study",
    x = "IWI",
    y = "fsscore"
  ) +
  ylim(0, NA) +
  xlim(0, 100) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )


# Print the plots
print(correlation_plot)
print(scatter_plot)
```

```{r combine plots, echo=FALSE}

# Combine the plots
plot_combined <- scatter_plot/ correlation_plot 

print(plot_combined)

```



```{r save plots, echo=FALSE}

# Save the combined plot
ggsave(here::here("output", "corr-iwi-fsscore-study.png"), 
       plot_combined, width = 11, height = 13, dpi = 300)

```
