---
title: "Stacked plot of IWI"
author: "Pearl Ante-Testard"
date: "`r Sys.Date()`"
output: pdf_document
  #officedown::rdocx_document
   # theme: default
    #highlight: default
    #code_folding: hide
    #toc: true
    #toc_depth: 3
    #toc_float:
      #collapsed: true
      #smooth_scroll: true
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, 
                          encoding   = encoding, 
                          output_dir = here::here("output")
                          )})
---

```{r clean environment, echo=FALSE}

rm(list=ls(all=TRUE))

```

```{r packages and functions, echo = TRUE, warning = FALSE}

source(here::here("R", "0-config.R"))

```

```{r read formatted data, echo=FALSE}

df_analysis <- readRDS(file = here::here("data", "1-final",
                      "df_analysis_iwi.rds")) %>% 
  dplyr::mutate(study = sub("s[0-9]*_", "", study.x)) %>%
  select(study, pid, study_id, region, cluster, arm_primary, iwi) %>% 
  dplyr::filter(!is.na(iwi)) %>%
  dplyr::mutate(iwi = as.numeric(iwi))

df_analysis_unique <- df_analysis %>%
  distinct(study_id, .keep_all = TRUE)
       
```

```{r stacked plot, echo = TRUE, warning = FALSE}

# Calculate frequency of each iwi bin
df_analysis_freq <- df_analysis_unique %>%
  mutate(iwi_bin = cut(iwi, breaks = c(-Inf, 0, seq(10, 100, by = 10)), 
                       include.lowest = TRUE)) %>%
  filter(!is.na(iwi_bin)) %>%
  group_by(iwi_bin, study) %>%
  summarize(frequency = n()) %>%
  ungroup() %>%
  arrange(frequency)

# Calculate the maximum iwi for each study and reorder the study factor levels
df_analysis <- df_analysis %>%
  group_by(study) %>%
  mutate(max_iwi = max(iwi)) %>%
  ungroup() %>%
  mutate(study = reorder(study, -max_iwi))

# Apply the same ordering to df_analysis_freq
df_analysis_freq <- df_analysis_freq %>%
  mutate(study = factor(study, levels = levels(df_analysis$study)))


# Generate a color palette
color_palette <- #hcl.colors(18, "Set3")
                c(brewer.pal(name="Set2", n = 8), brewer.pal(name="Dark2", n = 8))


df_analysis_freq <- df_analysis_freq %>%
  mutate(iwi_bin_num = case_when(iwi_bin == "[-Inf,0]" ~ 0, 
                                 iwi_bin == "(0,10]" ~ 1,
                                 iwi_bin == "(10,20]" ~ 2,
                                 iwi_bin == "(20,30]" ~ 3,
                                 iwi_bin == "(30,40]" ~ 4,
                                 iwi_bin == "(40,50]" ~ 5,
                                 iwi_bin == "(50,60]" ~ 6,
                                 iwi_bin == "(60,70]" ~ 7,
                                 iwi_bin == "(70,80]" ~ 8,
                                 iwi_bin == "(80,90]" ~ 9,
                                 iwi_bin == "(90,100]" ~ 10,
                                 TRUE ~ as.numeric(iwi_bin)))

df_analysis_density <- df_analysis_freq %>%
  group_by(study) %>%
  mutate(density = frequency / sum(frequency)) %>%
  ungroup()

stacked_plot <- ggplot(df_analysis_freq, aes(x = iwi_bin_num * 10, y = frequency, fill = study)) + 
  geom_area(linewidth = 0.5, colour = "black") +
  geom_vline(xintercept = 70, linetype = "dashed", color = "black") +
  scale_fill_manual(values = color_palette) +
  theme_minimal() +
  ylim(0, 14500) +
  scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 10)) +
  labs(x = "IWI", y = "Frequency", fill = "Study") +
  theme(legend.position = "none") +
  annotate("text", x = 50, y = 14000, label = "Binned by 10", hjust = 0.5, vjust = 1, size = 5, color = "black")

#stacked_plot <- ggplot(df_analysis_density, aes(x = iwi_bin_num * 10, y = density, fill = study)) + 
 # geom_area(linewidth = 0.5, colour = "black") +
 # geom_vline(xintercept = 70, linetype = "dashed", color = "black") +
 # scale_fill_manual(values = color_palette) +
 # theme_minimal() +
 # scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 10)) +
 # labs(x = "IWI", y = "Density", fill = "Study") +
 # theme(legend.position = "none") 

# Print the stacked plot
print(stacked_plot)

```

```{r other plots}

# Create the scatter plot
scatter_iwi <- ggplot(df_analysis, aes(x = iwi, y = study, color = study)) +
  geom_point() +
  scale_color_manual(values = color_palette) +
  geom_vline(xintercept = 70, linetype = "dashed", color = "black") +
  scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 10)) + # Ensure x-axis starts at 0 and set breaks
  theme_minimal() +
  labs(x = "IWI",
       y = "Study") +
  theme(
    legend.position = "none",
    axis.text.y = element_text(size = 7)  # Make y-axis font labels smaller
  ) +
  coord_fixed(ratio = 1.3)  # Adjust the aspect ratio to compress the height
  #annotate("text", x = 70, y = 20, label = "70", vjust = 1.5, color = "black") # Add annotation


# Print the plot
print(scatter_iwi)

```

```{r combine plot, echo = TRUE, warning = FALSE}

combined_plot <- stacked_plot / scatter_iwi 
combined_plot
```


```{r save plot, echo = TRUE, warning = FALSE}

# Save the plot
#ggsave(here::here("output", "stacked_iwi_studies.png"),
     #  plot = stacked_plot, width = 8, height = 6, dpi = 300)


#ggsave(here::here("output", "scatter_iwi.png"),
     #  plot = scatter_iwi, width = 8, height = 6, dpi = 300)

ggsave(here::here("output", "combined_iwi.png"),
       plot = combined_plot, width = 8, height = 8, dpi = 300)
```


Session info

```{r session info, echo = TRUE, warning = FALSE}
sessionInfo()
  
```